miner:
    # default miner MAC address
    mac: 00:0A:35:FF:FF:FF

build:
    # name of subdirectory in the build directory
    name: devel
    # file with default LEDE configuration
    config: defaults/devel.conf
    # always copy default configuration file
    config_always: no
    # relative or absolute path to the build directory
    dir: build
    # specifies the number of jobs to run simultaneously
    jobs: 4
    # show all commands during build process
    verbose: no
    # path to Xilinx SDK
    xilinx_sdk: ~/opt/xilinx/SDK/2017.2
    # target aliases for LEDE build system
    aliases:
        kernel: target/linux
        cgminer: package/utils/cgminer

remote:
    # default branch for repositories
    branch: braiins
    # always fetch latest source code
    fetch: no

    # list of remote repositories
    repos:
        lede:
            uri: git@gitlab.bo:x/lede.git
        luci:
            uri: git@gitlab.bo:x/luci.git
        linux:
            uri: git@gitlab.bo:x/linux-xlnx.git
        cgminer:
            uri: git@gitlab.bo:x/cgminer.git
            branch: braiins-old-spi

feeds:
    # always create feeds.conf
    create_always: no
    # always update feeds
    update_always: no
    # always install feeds
    install_always: no

deploy:
    # default target NAND or SD card
    target: sd
    # reboot miner after successful deploy
    reboot: yes
    # remove UUID from SD card
    remove_uuid: yes

    # setting for deploy over SSH connection
    ssh:
        # hostname suffix which is appended to generated hostname 'miner-xxyyzz'
        # where xxyyzz are last three numbers from MAC address
        hostname_suffix: .bo
        # ssh username
        username: root
        # ssh password
        password:
